version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
    depends_on:
      - mongo

  telegram-bot:
    build: .
    command: python -m app.telegram.telegram_bot
    depends_on:
      - web
  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
